#服务端口号
server:
  port: 8081
  #  服务的根路径
  servlet:
    context-path: /gmall
#设置数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gmall
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
#扫描MyBatis的xml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
# 控制台打印SQL
logging:
  level:
    com.example.demo.mapper: debug